/*
 *
 * https://projecteuler.net/problem=2
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
*/

function sumOfFibonacci(max, even = true) {
  let a = 1;
  let b = 1;
  let c = 2;
  let sum = 0;

  while (a<=max) {

    c = a + b;
    a = b;
    b = c;

    if (even === true && a % 2 === 0) {
      sum += a;
    } else if (even === false && a % 2 !== 0) {
      sum += a;
    }

  }
  return sum;
}

console.log(sumOfFibonacci(4000000)); // Answer = 4613732
